stages:
  - Build
  - Deployment

variables:
  VM_SSH_USER: azureuser
  VM_IP: 20.46.151.148

services:
  - docker:19.03.12

build:
  stage: Build
  before_script:
    #- apt-get update && apt-get install -y docker.io
    - echo "$DOCKER_REGISTRY_PASS" |  docker login --username "$DOCKER_REGISTRY_USER" --password-stdin
  script:
    - docker build -t $DOCKER_REGISTRY_USER/email-marketing-tool:api -f apps/api/Dockerfile .
    - docker push $DOCKER_REGISTRY_USER/email-marketing-tool:api

deploy:
  stage: Deployment
  before_script:
    - chmod 400 "$KEY_PEM"
  script:
    - echo "Deploying to Azure..."
    - ssh -o StrictHostKeyChecking=no -i "$KEY_PEM" $VM_SSH_USER@$VM_IP "docker-compose down -v &&
      docker-compose up -d &&
      docker-compose exec -T api sh -c \"cd packages/database && npx prisma migrate deploy\" "
  needs:
    - build
