stages:
  - Initialization
  - build
  - migrate
  - push
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
  SSH_HOST: "azureuser@20.46.151.148"

services:
  - docker:dind

before_script:
  - apt-get update && apt-get install -y docker-compose

docker_login:
  stage: Initialization
  script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS &&
    - echo "Logged in to the Docker registry"

build:
  stage: build
  script:
    - docker-compose build

migrate:
  stage: migrate
  script:
    - docker-compose up -d
    - docker-compose exec -T api sh -c "cd packages/database && npx prisma migrate dev --name init"
  dependencies:
    - build

docker_push:
  stage: push
  script:
    - docker tag saas-monorepo-api khalilbchir/email-marketing-tool:api
    - docker tag postgres:13 khalilbchir/email-marketing-tool:db
    - docker push khalilbchir/email-marketing-tool:api
    - docker push khalilbchir/email-marketing-tool:db
  dependencies:
    - migrate

deploy:
  stage: deploy
  script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - ssh -o StrictHostKeyChecking=no -i key.pem $SSH_HOST "echo 'Deployment successful.'"
  dependencies:
    - push
  api:
    image: khalilbchir/email-marketing-tool:api
    restart: always
    ports:
      - 8000:8000
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=jHDoohPu
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=saas-monorepo
      - SERVER_HOST=0.0.0.0
      - DATABASE_URL=postgresql://postgres:jHDoohPu@db:5432/saas-monorepo
    depends_on:
      - db
    privileged: true

  db:
    container_name: db
    image: khalilbchir/email-marketing-tool:db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=jHDoohPu
      - POSTGRES_DB=saas-monorepo

      test:
  stage: test
  before_script:
    - apt-get update && apt-get install -y docker-compose
  script:
    - docker-compose up -d
    - docker-compose exec -T api sh -c "cd packages/database && npx prisma migrate deploy"