version: "3"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 8000:8000
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=jHDoohPu
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=saas-monorepo
      - SERVER_HOST=0.0.0.0
      - DATABASE_URL=postgresql://postgres:jHDoohPu@db:5432/saas-monorepo
    depends_on:
      - db
    privileged: true

  db:
    container_name: db
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=jHDoohPu
      - POSTGRES_DB=saas-monorepo